apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wiki.name" . }}-password-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  value: placehole # replace me